version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - '80:8000'
    volumes:
      - ./app:/app
      - ./data:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:alpine3.15
    restart: always
    volumes:
      - dev-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-database:



