---
name: Continuous Deployment

on: push

jobs:
  test:
    name: Github Actions
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
      - name: Run Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint Testing
        run: docker-compose run --rm app sh -c "flake8"