---
name: Continuous Deployment

on: push

jobs:
  hello-gh-actions:
    name: Hello Github Actions
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Test
        run: echo "RUNNING TEST!"